### ISSUE TITLE
WASAPI (WDM) option to enable/disable usage of exclusive mode

### ISSUE THREAD

**Issue by Brynify** [onyx-and-iris/nvda-voicemeeter#13]
Hi there, I'm not sure if this would be possible, but it would be really great if you could add an option somewhere, probably advanced settings, to enable/disable WDM using exclusive mode.

**Comment by onyx-and-iris** [comment]
Hi. 

I don't think this is possible the API command seems to be disabled. I think it can only be done through the registry. I've forwarded a request to the devs for more info.

If I receive any updates I will write them in this issue thread.
