### ISSUE TITLE
Sliders for perametors for noise gate and compressor

### ISSUE THREAD

**Issue by Brynify** [onyx-and-iris/nvda-voicemeeter#14]
Hi there, it would be great if you could allow for changing the perametors if possible such as attack and release for gate and compressor.

**Comment by onyx-and-iris** [comment]
Hey,

Yes I can investigate this. Updates will be written in this issue thread.

**Comment by onyx-and-iris** [comment]
[Pre-release version](https://github.com/onyx-and-iris/nvda-voicemeeter/releases/tag/v.0.5.0.b1) now in Releases.
