### ISSUE TITLE
Noise Reduction (Denoiser) doesn't seem to work

### ISSUE THREAD

**Issue by masonasons** [onyx-and-iris/nvda-voicemeeter#15]
Hi, I'm trying to use the denoiser in Potato and changing the slider doesn't have any effect on the audio. Is this a bug or am I doing something wrong?

**Comment by onyx-and-iris** [comment]
Hello.

The denoiser slider is working but you should be aware that the Voicemeeter built in Denoiser is only a light one, so it won't remove any significant background noise. For example, it may remove the noise from a preamp but not a fan in the background.

There may be more options coming for the denoiser in a future release according to the devs but this is not confirmed.
