### ISSUE TITLE
❤ your screenshot!  Maybe drop it into your readme.md file

### ISSUE THREAD

**Issue by PySimpleGUI** [onyx-and-iris/nvda-voicemeeter#2]
Thank you for submitting your screenshot to the User Screenshots!  ![image](https://github.com/onyx-and-iris/nvda-voicemeeter/assets/46163555/7ee92487-a352-415d-a9b0-fd68f6df010c)

It's great to see people sharing their work.  Since PySimpleGUI programs are visual, a screenshot goes a long ways, especially with visitors to repos.

The same code the GitHub produces when you paste a screenshot into a GitHub issue can be copied directly into your readme.

When you pasted the screenshot into the PySimpleGUI Issue:

![image](https://github.com/PySimpleGUI/PySimpleGUI/assets/55352169/f99212f5-1870-4387-ba4c-159dd40d4c8e)

GitHub added this code to the comment:

`![image](https://github.com/PySimpleGUI/PySimpleGUI/assets/55352169/f99212f5-1870-4387-ba4c-159dd40d4c8e)
https://github.com/onyx-and-iris/nvda-voicemeeter`

You can do the same here... paste the image into a GitHub issue, the edit the command and copy the line of text like the one above.  If you paste this into your readme.md file, then it'll be embedded in the readme that's shown to visitors.

Great job creating a nice looking interface!

**Comment by onyx-and-iris** [comment]
Hey, thanks for the feedback, you've created a very interesting framework with PySimpleGUI, it was a pleasure to work with.

b2e03aace1d1327290f4ad0bad1544b3f666ba51 adds a screenshot

**Comment by PySimpleGUI** [comment]
Glad you enjoyed the experience!  Fun...it's the number one goal of the project.
